/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#faf8ff',
        'primary-container': '#6e9fff',
        'surface-tint': '#85adff',
        'secondary-fixed-dim': '#ceb9ff',
        'on-primary-fixed-variant': '#002a62',
        'error-dim': '#d7383b',
        'on-primary-container': '#002150',
        'surface-variant': '#1c253e',
        'surface-container': '#11192e',
        'on-surface': '#dfe4fe',
        'on-secondary-fixed-variant': '#5f28c8',
        'on-tertiary': '#5b5f65',
        'on-error-container': '#ffa8a3',
        secondary: '#ac8aff',
        'on-background': '#dfe4fe',
        'on-tertiary-container': '#53575c',
        'on-surface-variant': '#a5aac2',
        'on-secondary-container': '#d9c8ff',
        outline: '#6f758b',
        'surface-dim': '#070d1f',
        'surface-container-highest': '#1c253e',
        error: '#ff716c',
        background: '#070d1f',
        'inverse-on-surface': '#4f5469',
        'on-secondary-fixed': '#40009b',
        'error-container': '#9f0519',
        surface: '#070d1f',
        'primary-fixed': '#6e9fff',
        tertiary: '#f6f9ff',
        'secondary-container': '#5516be',
        'on-tertiary-fixed': '#474c51',
        'on-tertiary-fixed-variant': '#64686e',
        'secondary-dim': '#8455ef',
        'outline-variant': '#41475b',
        primary: '#85adff',
        'surface-container-high': '#171f36',
        'on-primary-fixed': '#000000',
        'tertiary-fixed-dim': '#e5e8ee',
        'primary-fixed-dim': '#5391ff',
        'tertiary-dim': '#e5e8ee',
        'tertiary-container': '#e7ebf1',
        'on-secondary': '#280067',
        'secondary-fixed': '#dac9ff',
        'primary-dim': '#699cff',
        'inverse-primary': '#005bc4',
        'surface-container-lowest': '#000000',
        'tertiary-fixed': '#f3f7fd',
        'on-error': '#490006',
        'surface-container-low': '#0c1326',
        'on-primary': '#002c66',
        'surface-bright': '#222b47',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
