"""한↔영 쿼리 확장 — 의미 동일 다국어 토큰을 검색 쿼리에 추가.

배경:
  BGE-M3 dense 임베딩은 다국어 의미를 잘 포착하지만, sparse 채널과
  ASF token 매칭은 정확한 토큰 일치만 가능 → '어린이' 와 'children' 검색
  결과가 달라짐.

해결:
  검색 시점에 query 를 자동 확장:
    '어린이' → '어린이 children kids child'
    'children' → 'children 어린이 아이들'
  이렇게 하면 sparse + ASF 도 다국어 토큰 모두 커버.

사용:
  from services.query_expand import expand_bilingual
  expanded = expand_bilingual('어린이')  # '어린이 children kids child'
"""
from __future__ import annotations
import re

# 한↔영 양방향 사전 — 데이터셋 도메인 특화 + 일반 명사
# 도메인: 뉴스/방송, 스포츠, 연예/엔터, 정치, 경제/금융, 기술/AI,
#          의료/과학, 사회/생활, 문서/업무, 음악(BGM), 이미지 묘사
_KO_EN: dict[str, list[str]] = {

    # ── 인물 / 사람 ────────────────────────────────────────────────
    "어린이":       ["children", "kids", "child"],
    "아이들":       ["children", "kids"],
    "아이":         ["child", "kid"],
    "아기":         ["baby", "infant", "toddler"],
    "유아":         ["infant", "toddler", "baby"],
    "꼬맹이":       ["kid", "toddler", "child"],
    "아가":         ["baby", "infant"],
    "신생아":       ["newborn", "infant", "baby"],
    "사람":         ["person", "people"],
    "인물":         ["person", "portrait"],
    "여성":         ["woman", "female", "women"],
    "남성":         ["man", "male", "men"],
    "학생":           ["student", "pupil"],
    "선생":         ["teacher"],
    "교사":           ["teacher", "educator"],
    "노인":         ["elderly", "senior"],
    "가족":         ["family"],
    "시민":         ["citizen", "public"],
    "국민":         ["citizen", "people", "public"],
    "전문가":       ["expert", "specialist"],
    "의원":         ["lawmaker", "congressman", "politician"],
    "장관":         ["minister", "secretary"],
    "대통령":       ["president"],
    "기자":         ["reporter", "journalist"],
    "앵커":         ["anchor", "newscaster"],
    "아나운서":     ["announcer", "newscaster"],
    "선수":         ["athlete", "player"],
    "감독":         ["director", "coach", "manager"],
    "배우":         ["actor", "actress"],
    "가수":         ["singer", "artist"],
    "연예인":       ["celebrity", "entertainer", "star"],
    "아이돌":       ["idol", "kpop idol"],
    "유튜버":       ["youtuber", "creator", "influencer"],
    "인스타그램":   ["instagram", "social media", "SNS"],
    "트위터":       ["twitter", "tweet", "social media"],
    "트윗":         ["tweet", "twitter"],
    "블로그":       ["blog", "blogger"],
    "포스팅":       ["post", "posting", "blog post"],
    "콘텐츠":       ["content", "contents", "media"],
    "크리에이터":   ["creator", "content creator", "youtuber"],
    "SNS":          ["social media", "social network", "platform"],
    "소셜":         ["social", "social media", "SNS"],
    "스트리밍":     ["streaming", "stream", "OTT"],
    "넷플릭스":     ["Netflix", "streaming", "OTT"],
    "OTT":          ["OTT", "streaming", "on-demand"],
    "회장":         ["chairman", "president", "CEO"],
    "대표":         ["representative", "CEO", "president"],
    "교수":         ["professor"],
    "의사":         ["doctor", "physician"],
    "변호사":       ["lawyer", "attorney"],
    "검사":         ["prosecutor"],
    "판사":         ["judge"],

    # ── 장소 / 공간 ────────────────────────────────────────────────
    # (바다/산/강/호수는 아래 동물/자연물 섹션에 더 완전한 형태로 정의됨)
    "산맥":         ["mountain range", "mountains"],
    "도시":         ["city", "urban"],
    "건물":         ["building", "structure"],
    "공원":         ["park", "outdoor park"],
    "정원":         ["garden", "yard"],
    "동물":           ["animal", "animals", "creature", "wildlife"],
    "동물원":       ["zoo", "animal park"],
    "아파트":          ["apartment", "apartment complex", "flat"],
    "야경":           ["night view", "night scene", "city lights", "cityscape", "nightscape"],
    "밤하늘":          ["night sky", "starry night", "stars at night"],
    "하늘":           ["sky", "heavens", "heaven"],
    "구름":           ["cloud", "clouds"],
    "눈":           ["snow", "eye"],
    "비":           ["rain", "rainfall"],
    "바람":         ["wind"],
    "안개":         ["fog", "mist", "haze"],
    "무지개":       ["rainbow"],
    "석양":           ["sunset", "evening glow", "dusk"],
    "학교":           ["school"],
    "대학":           ['university', 'college'],
    "회사":         ["company", "office", "corporation"],
    "사무실":       ["office"],
    "도서관":       ["library"],
    "박물관":       ["museum"],
    "병원":         ["hospital", "clinic"],
    "법원":         ["court", "courthouse"],
    "국회":         ["parliament", "national assembly", "congress"],
    "청와대":       ["blue house", "presidential office"],
    "경찰":           ["police", "law enforcement"],
    "검찰":         ["prosecution", "prosecutor's office"],
    "공항":         ["airport"],
    "항구":         ["port", "harbor"],
    "공장":         ["factory", "plant"],
    "식당":           ["restaurant", "dining", "eatery"],
    "가게":         ["store", "shop"],
    "시장":         ["market"],
    "백화점":       ["department store"],
    "지하철":       ["subway", "metro"],
    "버스":         ["bus"],

    # ── 동물 / 자연물 ──────────────────────────────────────────────
    "고양이":       ["cat", "kitten", "feline", "kitty"],
    "반려묘":       ["cat", "pet cat", "feline", "kitty"],
    "강아지":       ["dog", "puppy", "canine", "반려견"],
    "반려견":       ["dog", "pet dog", "puppy", "canine"],
    "반려동물":     ["pet", "companion animal", "domestic animal"],
    "개":           ["dog", "canine"],
    "새":           ["bird", "avian"],
    "물고기":       ["fish", "aquatic animal"],
    "토끼":         ["rabbit", "bunny"],
    "햄스터":       ["hamster", "rodent"],
    "곰":           ["bear"],
    "사자":         ["lion"],
    "호랑이":       ["tiger"],
    "코끼리":       ["elephant"],
    "꽃":            ["flower", "flowers", "blossom", "floral", "bloom", "petal", "bouquet"],
    "꽃잎":         ["petal", "petals", "flower petal"],
    "꽃다발":       ["bouquet", "bunch of flowers"],
    "식물":           ["plant", "plants", "vegetation", "flora"],
    "나무":           ["tree", "trees", "forest wood"],
    "잔디":         ["grass", "lawn", "turf"],
    "풀":           ["grass", "herb", "plant"],
    "열매":         ["fruit", "berry", "berries"],
    "과일":         ["fruit", "fruits"],
    "사과":         ["apple", "apples", "fruit"],
    "씨앗":         ["seed", "seeds"],
    "잎":           ["leaf", "leaves", "foliage"],
    "가지":         ["branch", "twig", "stem"],
    "뿌리":         ["root", "roots"],
    # 자연 풍경
    "자연":           ["nature", "natural", "outdoor", "wildlife"],
    "풍경":           ["landscape", "scenery", "scene", "view"],
    "경치":         ["scenery", "landscape", "view"],
    "산":           ["mountain", "mountains", "hill"],
    "바다":         ["sea", "ocean", "beach", "coast"],
    "강":           ["river", "stream"],
    "숲":           ["forest", "woods", "woodland"],
    "들판":         ["field", "meadow", "plain"],
    "해변":         ["beach", "seashore", "coast"],
    "호수":         ["lake", "pond"],
    "폭포":         ["waterfall", "falls"],
    "노을":         ["sunset", "dusk", "golden hour", "twilight"],
    "일몰":         ["sunset", "dusk", "sundown"],
    "일출":         ["sunrise", "dawn"],

    # ── 사물 ──────────────────────────────────────────────────────
    "노트북":       ["laptop", "notebook"],
    "컴퓨터":       ["computer", "PC"],
    "스마트폰":     ["smartphone", "phone", "mobile"],
    "자동차":       ["car", "vehicle", "automobile"],
    "차":           ["car", "vehicle"],
    "운전":         ["driving", "drive"],
    "음식":         ['food', 'meal', 'dish', 'cuisine'],
    "요리":         ['cooking', 'cuisine', 'food', 'dish', 'recipe'],
    "한식":         ["Korean food", "Korean cuisine", "Korean dish"],
    "한국음식":     ["Korean food", "Korean cuisine", "Korean dish"],
    "한국요리":     ["Korean cuisine", "Korean cooking", "Korean food"],
    "김치":         ["kimchi", "Korean fermented vegetable"],
    "비빔밥":       ["bibimbap", "Korean rice bowl"],
    "불고기":       ["bulgogi", "Korean BBQ beef"],
    "삼겹살":       ['samgyeopsal', 'Korean pork belly', 'Korean BBQ', 'pork belly', 'BBQ pork'],
    "떡볶이":       ["tteokbokki", "spicy rice cake"],
    "냉면":         ["naengmyeon", "cold noodles"],
    "된장":         ["doenjang", "Korean soybean paste"],
    "간장":         ["soy sauce", "ganjang"],
    "케이크":       ["cake", "dessert"],
    "피자":         ["pizza"],
    "커피":         ["coffee"],
    "음료":         ["drink", "beverage"],
    "옷":           ["clothes", "clothing", "outfit"],
    "패션":         ["fashion", "style"],
    "가방":         ["bag", "handbag", "backpack"],
    "신발":         ["shoes", "footwear"],
    "책":           ["book"],
    "문서":         ["document", "paper"],
    "사진":         ["photo", "photograph", "picture"],
    "그림":         ["drawing", "picture", "image", "painting"],
    "풍경화":       ["landscape painting", "landscape art"],
    "카메라":       ["camera"],
    "인형":         ["doll", "stuffed animal", "plush toy", "toy"],
    "봉제인형":     ["stuffed toy", "plush", "plush doll", "stuffed animal"],
    "장난감":       ["toy", "toys"],
    "셀카":         ["selfie", "self-portrait"],
    "셀피":         ["selfie", "self-portrait"],
    # 공간 유형
    "실내":         ["indoor", "indoors", "interior"],
    "실외":         ["outdoor", "outdoors", "exterior"],
    "야외":         ["outdoor", "outdoors", "outside"],
    "주방":         ["kitchen", "cooking area"],
    "거실":         ["living room", "lounge"],
    "침실":         ["bedroom"],
    "욕실":         ["bathroom"],
    "서재":         ["study room", "home office"],
    "인테리어":     ["interior", "decor", "interior design", "home design"],
    "가구":         ["furniture", "furnishing", "furnishings"],
    "책상":         ["desk", "table", "writing desk"],
    "의자":         ["chair", "seat", "seating"],
    "소파":         ["sofa", "couch", "settee"],
    "침대":         ["bed", "sleeping area"],
    "옷장":         ["wardrobe", "closet", "cabinet"],
    "선반":         ["shelf", "shelves", "rack"],
    "장식":         ["decoration", "decor", "ornament"],
    "텍스처":       ["texture", "material", "surface"],
    "패턴":         ["pattern", "design", "motif"],
    "배경":         ["background", "backdrop", "setting"],
    "표면":         ["surface", "texture", "material"],
    "질감":         ["texture", "feel", "surface quality"],
    "무늬":         ["pattern", "motif", "design"],
    "그라데이션":   ["gradient", "color gradient", "gradation"],
    # EN→KO 실내/가구/텍스처 역방향
    "interior":     ["실내", "인테리어"],
    "decor":        ["인테리어", "장식"],
    "furniture":    ["가구", "가구류"],
    "desk":         ["책상", "탁자"],
    "chair":        ["의자"],
    "sofa":         ["소파"],
    "bed":          ["침대"],
    "shelf":        ["선반"],
    "texture":      ["텍스처", "질감"],
    "pattern":      ["패턴", "무늬"],
    "background":   ["배경"],
    "surface":      ["표면", "질감"],
    "gradient":     ["그라데이션", "색조"],
    "apple":        ["사과", "과일"],

    # ── 뉴스 / 방송 ────────────────────────────────────────────────
    "뉴스":         ["news", "broadcast"],
    "방송":         ["broadcast", "broadcasting", "media"],
    "라디오":       ["radio", "broadcast"],
    "프로그램":     ["program", "show"],
    "토론":         ["debate", "discussion"],
    "인터뷰":       ["interview"],
    "팟캐스트":     ["podcast"],
    "취재":         ["coverage", "reporting", "investigation"],
    "보도":         ["report", "coverage", "news report"],
    "속보":         ["breaking news"],
    "단독":           ["exclusive", "scoop"],
    "기사":         ["article", "news article", "story"],
    "특보":         ["special report"],
    "논평":         ["commentary", "editorial"],
    "해설":         ["analysis", "commentary", "explanation"],
    "사설":         ["editorial"],
    "여론":         ["public opinion", "opinion poll"],
    "조사":         ["survey", "investigation", "research"],

    # ── 스포츠 ────────────────────────────────────────────────────
    "스포츠":       ["sports", "sport", "athletics", "athletic"],
    "체육":         ["physical education", "PE", "athletics", "sports"],
    "운동":         ["exercise", "workout", "sport", "athletics", "physical activity"],
    "체조":         ["gymnastics", "gymnastics sport"],
    "육상":         ["track and field", "athletics"],
    "마라톤":          ["marathon", "long distance running", "running race"],
    "사이클링":     ["cycling", "bicycle race"],
    "볼링":         ["bowling"],
    "아이스하키":   ["ice hockey"],
    "스케이팅":     ["skating", "ice skating"],
    # EN→KO 역방향 (스포츠)
    "sport":        ["스포츠", "운동"],
    "sports":       ["스포츠", "운동", "체육"],
    "athletics":    ["체육", "스포츠", "운동"],
    "athletic":     ["스포츠", "운동선수"],
    "exercise":     ["운동", "체육"],
    "workout":      ["운동", "트레이닝"],
    "championship": ["챔피언십", "결승", "선수권"],
    "olympic":      ["올림픽"],
    "marathon":     ["마라톤"],
    "basketball":   ["농구"],
    "baseball":     ["야구"],
    "soccer":       ["축구"],
    "football":     ["축구", "풋볼"],
    "volleyball":   ["배구"],
    "tennis":       ["테니스"],
    "boxing":       ["권투", "복싱"],
    "swimming":     ["수영"],
    "golf":         ["골프"],
    "농구":         ["basketball"],
    "야구":         ["baseball"],
    "축구":         ["soccer", "football"],
    "배구":         ["volleyball"],
    "골프":         ["golf"],
    "수영":           ["swimming", "swim"],
    "테니스":       ["tennis"],
    "럭비":         ["rugby"],
    "스키":           ["skiing", "ski", "winter sport"],
    "격투":         ["fighting", "combat sport"],
    "권투":         ["boxing"],
    "씨름":         ["Korean wrestling", "ssireum"],
    "태권도":       ["taekwondo"],
    "올림픽":       ["Olympics", "Olympic"],
    "월드컵":       ["World Cup"],
    "리그":         ["league"],
    "하이라이트":   ["highlight", "highlights"],
    "결승":         ["final", "championship"],
    "득점":         ["score", "goal"],
    "경기":         ["game", "match", "competition"],
    "승리":         ["victory", "win"],
    "패배":         ["defeat", "loss"],
    "선발":         ["starting lineup", "selection"],
    "플레이오프":   ["playoffs"],
    "챔피언":       ["champion", "championship"],
    "국가대표":     ["national team", "national representative"],
    "프로":         ["professional", "pro"],
    "홈런":         ["home run", "homer", "homerun", "home-run"],
    "안타":         ["hit", "base hit", "single", "double", "triple"],
    "투수":         ["pitcher", "pitcher baseball"],
    "타자":         ["batter", "hitter", "batting"],
    "포수":         ["catcher", "catcher baseball"],
    # EN single-word → KO expansions (for "soccer national team" tokenized as ["soccer","national","team"])
    "national":     ["국가대표", "국내"],
    "team":         ["팀", "국가대표"],
    # 이미지 도메인 EN→KO (영어 쿼리로 한국어 캡션 매칭)
    "cat":          ["고양이", "반려묘"],
    "kitten":       ["고양이", "새끼고양이"],
    "dog":          ["강아지", "개", "반려견"],
    "puppy":        ["강아지", "새끼강아지"],
    "bird":         ["새", "조류"],
    "rabbit":       ["토끼"],
    "flower":       ["꽃", "꽃잎"],
    "mountain":     ["산", "산악"],
    "beach":        ["해변", "바다"],
    "ocean":        ["바다", "해양"],
    "forest":       ["숲", "나무"],
    "sunset":       ["노을", "일몰", "석양"],
    "sunrise":      ["일출"],
    "indoor":       ["실내"],
    "outdoor":      ["야외", "실외"],
    "doll":         ["인형", "봉제인형"],
    "stuffed":      ["봉제인형", "인형", "봉제", "plush"],
    "plush":        ["봉제인형", "인형", "봉제"],
    "toy":          ["장난감", "인형"],
    "selfie":       ["셀카", "셀피"],
    "food":         ['음식', '요리', '한식', '식량', '식품', '먹거리'],
    "cooking":      ['요리', '음식'],
    "kimchi":       ["김치", "한식"],
    "bibimbap":     ["비빔밥", "한식"],
    "bulgogi":      ["불고기", "한식", "BBQ"],
    "cuisine":      ["음식", "요리", "한식"],
    "kitchen":      ["주방", "부엌"],
    "car":          ["자동차", "차"],
    "pet":          ["반려동물", "고양이"],  # 강아지 제거 — _EN_KO["강아지"]→["pet"] 역전 버그 방지
    "portrait":     ["인물", "초상"],
    "landscape":    ["풍경", "경치", "경관"],
    "animal":       ["동물", "반려동물"],
    "nature":       ["자연", "풍경", "자연환경"],
    "sky":          ["하늘"],
    "cloud":        ["구름"],
    "snow":         ["눈", "설경"],
    "rain":         ["비"],
    "night":        ["밤", "야경"],
    "city":         ["도시", "도시풍경"],
    "street":       ["거리", "도로"],
    "person":       ["사람", "인물"],
    "people":       ["사람들", "인물"],
    "woman":        ["여성", "여자"],
    "man":          ["남성", "남자"],
    "child":        ["아이", "어린이"],
    "children":     ["아이들", "어린이"],

    # ── 연예 / 엔터테인먼트 ────────────────────────────────────────
    "드라마":       ["drama", "TV show", "series"],
    "영화":         ["movie", "film", "cinema"],
    "예능":         ["variety show", "entertainment show"],
    "시트콤":       ["sitcom"],
    "다큐멘터리":   ["documentary"],
    "콘서트":       ["concert"],
    "공연":           ["performance", "show", "concert"],
    "연예대상":         ["entertainment award", "broadcasting award", "entertainment awards", "MBC awards"],
    "시상식":          ["award ceremony", "awards", "awards show", "ceremony"],
    "음반":         ["album", "record"],
    "데뷔":         ["debut"],
    "기획사":       ["agency", "entertainment company"],
    "소속사":       ["agency", "management company"],
    "팬":           ["fan", "fans"],
    "뮤직비디오":   ["music video", "MV"],
    "코미디":       ["comedy"],
    "로맨스":       ["romance"],
    "액션":         ["action"],
    "스릴러":       ["thriller"],
    "공포":         ["horror"],
    "케이드라마":   ["kdrama", "korean drama", "K-drama"],
    "웹툰":         ["webtoon", "manhwa", "korean comics"],
    "만화":         ["comic", "cartoon", "manga"],
    "만화책":       ["comic book", "graphic novel"],
    "유튜브":       ["youtube", "YouTube"],
    "영상":         ["video", "clip", "footage"],
    "채널":         ["channel", "media channel"],
    "시청":         ["watch", "viewing"],
    # EN→KO 연예/엔터 역방향
    "entertainment": ["연예", "엔터테인먼트", "예능"],
    "celebrity":    ["연예인", "유명인", "스타"],
    "movie":        ["영화", "영화작품"],
    "film":         ["영화", "필름", "작품"],
    "drama":        ["드라마", "연극"],
    "variety":      ["예능", "버라이어티"],
    "broadcaster":  ["방송인", "방송"],
    "comedy":       ["코미디", "개그"],
    "thriller":     ["스릴러", "공포"],
    "horror":       ["공포", "호러", "공포영화"],
    "romance":      ["로맨스", "연애"],
    "action":       ["액션", "행동"],
    "kdrama":       ["케이드라마", "한국드라마", "드라마"],
    "webtoon":      ["웹툰", "만화"],
    "manhwa":       ["웹툰", "만화"],
    "comic":        ["만화", "만화책"],
    "youtube":      ["유튜브", "영상"],
    "channel":      ["채널", "방송채널"],
    "video":        ["영상", "동영상"],
    "watch":        ["시청", "보기"],
    "album":        ["음반", "앨범"],
    "debut":        ["데뷔", "첫등장"],
    "homer":        ["홈런", "야구"],
    "homerun":      ["홈런", "야구"],

    # ── 정치 ──────────────────────────────────────────────────────
    "정치":         ["politics", "political"],
    "정부":         ["government"],
    "선거":         ["election", "vote"],
    "투표":         ["vote", "voting", "ballot"],
    "탄핵":         ["impeachment"],
    "계엄":         ["martial law"],
    "여당":         ["ruling party", "government party"],
    "야당":         ["opposition party"],
    "국정":         ["state affairs", "government affairs"],
    "공천":         ["nomination", "party nomination"],
    "대선":         ["presidential election"],
    "총선":         ["general election"],
    "지선":         ["local election"],
    "헌법":         ["constitution", "constitutional"],
    "법":           ["law", "legal"],
    "법안":         ["bill", "legislation"],
    "개헌":         ["constitutional amendment"],
    "특검":         ["special prosecutor", "special investigation"],
    "검찰개혁":     ["prosecution reform"],
    "청문회":       ["confirmation hearing"],
    # EN→KO 정치 역방향
    "politics":     ["정치"],
    "political":    ["정치적", "정치"],
    "election":     ["선거", "선거운동"],
    "vote":         ["투표", "선거"],
    "voting":       ["투표", "선거"],
    "government":   ["정부", "국정"],
    "parliament":   ["국회", "의회"],
    "congress":     ["국회", "의회"],
    "impeachment":  ["탄핵"],
    "presidential": ["대통령", "대선"],
    "democracy":    ["민주주의", "민주"],
    "policy":       ["정책"],
    "constitution": ["헌법", "헌법적"],

    # ── 경제 / 금융 ────────────────────────────────────────────────
    "경제":         ["economy", "economic"],
    "금융":         ["finance", "financial"],
    "주식":         ["stock", "stocks", "shares"],
    "증시":         ["stock market", "stock exchange"],
    "코스피":       ["KOSPI", "Korea stock index"],
    "코스닥":       ["KOSDAQ"],
    "부동산":       ["real estate", "property", "housing"],
    "아파트값":     ["apartment price", "housing price"],
    "집값":         ["housing price", "home price", "property price", "apartment price"],
    "주택":         ["housing", "house", "residential"],
    "금리":         ["interest rate"],
    "환율":         ["exchange rate", "currency"],
    "물가":         ["price", "inflation", "cost of living"],
    "인플레이션":   ["inflation"],
    "경기침체":     ["recession", "economic downturn"],
    "성장":         ["growth"],
    "GDP":          ["GDP", "gross domestic product"],
    "수출":         ["export", "exports"],
    "수입":         ["import", "imports"],
    "무역":         ["trade"],
    "관세":         ["tariff", "customs"],
    "스타트업":     ["startup"],
    "투자":         ["investment", "invest"],
    "펀드":         ["fund"],
    "채권":         ["bond", "bonds"],
    "가상화폐":     ["cryptocurrency", "crypto", "bitcoin"],
    "비트코인":     ["bitcoin", "cryptocurrency"],
    "은행":         ["bank", "banking"],
    "보험":         ["insurance"],
    "연금":         ["pension"],
    "예산":         ["budget", "fiscal"],
    "세금":         ["tax", "taxes"],
    "복지":         ["welfare", "social welfare"],
    # EN→KO 경제/금융 역방향
    "economy":      ["경제"],
    "economic":     ["경제적", "경제"],
    "finance":      ["금융", "재정"],
    "financial":    ["금융", "재정적"],
    "stock":        ["주식"],
    "stocks":       ["주식"],
    "investment":   ["투자"],
    "invest":       ["투자"],
    "investor":     ["투자자"],
    "market":       ["시장"],
    "trade":        ["무역", "거래"],
    "inflation":    ["인플레이션", "물가"],
    "recession":    ["경기침체", "불황"],
    "budget":       ["예산", "예산안"],
    "tax":          ["세금", "세율"],
    "fund":         ["펀드", "기금"],
    "bitcoin":      ["비트코인", "가상화폐"],
    "crypto":       ["가상화폐", "암호화폐"],
    "cryptocurrency": ["가상화폐", "암호화폐"],
    "startup":      ["스타트업", "창업"],
    "bank":         ["은행", "금융"],
    "insurance":    ["보험"],
    "welfare":      ["복지", "사회복지"],
    "housing":      ["주택", "부동산", "집값", "아파트"],
    "property":     ["부동산", "재산", "자산"],
    "residential":  ["주거", "주택", "거주"],
    "prices":       ["가격", "물가", "집값"],
    "price":        ["가격", "값", "물가"],

    # ── 기술 / AI ──────────────────────────────────────────────────
    "기술":         ["technology", "technical", "tech"],
    "인공지능":     ["AI", "artificial intelligence", "machine learning", "deep learning"],
    "머신러닝":     ["machine learning", "ML", "AI", "deep learning"],
    "기계학습":     ["machine learning", "ML", "AI"],
    "딥러닝":       ["deep learning", "neural network", "AI"],
    "신경망":       ["neural network", "deep learning", "neural net"],
    "AI":           ["AI", "인공지능", "artificial intelligence"],
    "LLM":          ["LLM", "large language model", "언어모델"],
    # ── 복합명사 (doc 도메인 고빈도) ─────────────────────────────────
    "인공지능산업":  ["AI industry", "artificial intelligence industry"],
    "소프트웨어산업": ["software industry", "SW industry"],
    "반도체산업":   ["semiconductor industry"],
    "정보통신":     ["information communication", "ICT"],
    "ICT":          ["정보통신", "ICT", "information technology"],
    "정보기술":     ["information technology", "IT"],
    "디지털전환":   ["digital transformation", "DX"],
    "디지털경제":   ["digital economy"],
    "스마트시티":   ["smart city"],
    "데이터경제":   ["data economy"],
    "클라우드컴퓨팅": ["cloud computing"],
    "사이버보안":   ["cybersecurity", "information security"],
    "생성형":       ["generative", "generative AI"],
    # ── VR / AR / XR ────────────────────────────────────────────────
    "가상현실":     ["virtual reality", "VR", "VR experience"],
    "증강현실":     ["augmented reality", "AR", "AR experience"],
    "혼합현실":     ["mixed reality", "XR", "MR"],
    "vr":           ["가상현실", "virtual reality"],
    "ar":           ["증강현실", "augmented reality"],
    "xr":           ["혼합현실", "XR", "가상현실", "증강현실"],
    "virtual":      ["가상", "가상현실"],
    "augmented":    ["증강", "증강현실"],
    # ── e-learning ──────────────────────────────────────────────────
    "이러닝":       ["e-learning", "online learning", "digital learning"],
    "온라인교육":   ["online education", "e-learning", "distance learning"],
    "e-learning":   ["이러닝", "온라인 학습", "온라인교육"],
    "elearning":    ["이러닝", "온라인 학습"],
    # ── SaaS ────────────────────────────────────────────────────────
    "saas":         ["SaaS", "software as a service", "서비스형 소프트웨어"],
    "서비스형소프트웨어": ["SaaS", "software as a service"],
    # ── AI/ML 모델 아키텍처 (논문 검색 대응) ────────────────────────
    "트랜스포머":   ["transformer", "transformer model", "attention mechanism"],
    "어텐션":       ["attention", "self-attention", "attention mechanism"],
    "자기어텐션":   ["self-attention", "multi-head attention"],
    "bert":         ["BERT", "language model", "언어모델", "사전학습"],
    "transformer":  ["트랜스포머", "언어모델", "attention"],
    "attention":    ["어텐션", "self-attention", "주목"],
    # ── SPRI / SW산업 (문서 특화) ───────────────────────────────────
    "spri":         ["SPRI", "소프트웨어정책연구소", "SW 정책"],
    "소프트웨어정책연구소": ["SPRI", "SW Policy Research Institute"],
    "sw":           ["software", "소프트웨어"],
    # EN single-word → KO expansions (for "artificial intelligence" query tokenized as ["artificial","intelligence"])
    "artificial":   ["인공지능", "AI"],
    "intelligence": ["인공지능", "AI"],
    "machine":      ["머신러닝", "기계학습", "기계"],
    "learning":     ["머신러닝", "기계학습", "딥러닝"],
    "neural":       ["신경망", "딥러닝", "신경", "뇌"],
    "network":      ["네트워크", "신경망"],
    "deep":         ["딥러닝", "심층"],
    "dataset":      ["데이터셋", "데이터"],
    "model":        ["모델", "AI모델"],
    "챗봇":         ["chatbot", "AI assistant"],
    "자율주행":     ["autonomous driving", "self-driving"],
    "반도체":       ["semiconductor", "chip"],
    "소프트웨어":   ["software"],
    "하드웨어":     ["hardware"],
    "플랫폼":       ["platform"],
    "클라우드":     ["cloud", "cloud computing"],
    "빅데이터":     ["big data", "data analytics"],
    "사이버":       ["cyber", "cybersecurity"],
    "해킹":         ["hacking", "hack", "cyberattack"],
    "드론":         ["drone", "UAV"],
    "로봇":         ["robot", "robotics"],
    "전기차":       ["electric vehicle", "EV", "electric car"],
    "배터리":       ["battery"],
    "태양광":       ["solar", "solar energy", "photovoltaic"],
    "신재생":       ["renewable energy", "clean energy"],
    "탄소":         ["carbon", "CO2"],
    "에너지":       ["energy", "power"],
    "전기":         ["electricity", "electric", "power"],
    "기후변화":     ["climate change", "global warming"],
    "온난화":       ["global warming", "warming", "temperature rise", "climate change"],
    "지구온난화":   ["global warming", "climate crisis", "warming", "climate change"],
    "기온":         ["temperature", "climate", "degree"],
    "온도":         ["temperature", "degree"],
    "자동화":       ["automation", "automated"],
    "인터넷":       ["internet", "web", "online"],
    "소셜미디어":   ["social media", "SNS"],
    "영어":         ["English", "English language"],
    "한국어":       ["Korean", "Korean language"],
    # EN→KO 공백 보완 (multi-word KO 개념에 대한 단일어 EN 역방향)
    "autonomous":   ["자율주행", "자율"],
    "energy":       ["에너지", "신재생"],
    "electric":     ["전기", "전기차"],
    "internet":     ["인터넷", "온라인"],
    "automation":   ["자동화", "자율"],
    "english":      ["영어"],
    "디지털":       ["digital"],
    "온라인":       ["online"],
    "메타버스":     ["metaverse", "virtual reality", "VR"],
    "데이터":       ["data", "dataset", "database"],
    "데이터센터":   ["data center", "datacenter"],
    "정보":         ["information"],
    "보안":         ["security", "cybersecurity"],
    "앱":           ["app", "application"],

    # ── 의료 / 과학 / 건강 ─────────────────────────────────────────
    "의료":         ["medical", "healthcare", "medicine"],
    "건강":         ["health", "healthy"],
    "질병":         ["disease", "illness"],
    "수면":         ["sleep", "sleeping", "rest"],
    "불면증":       ["insomnia", "sleep disorder", "sleeplessness"],
    "잠":           ["sleep", "rest", "nap"],
    "술":           ["alcohol", "drink", "liquor", "beverage"],
    "맥주":         ["beer", "ale", "alcohol"],
    "와인":         ["wine", "alcohol"],
    "치킨":         ["chicken", "fried chicken"],
    "고기":         ["meat", "beef", "pork", "flesh"],
    "레시피":       ["recipe", "cooking", "how to cook"],
    "코로나":       ["COVID", "coronavirus", "pandemic"],
    "백신":         ["vaccine", "vaccination"],
    "암":           ["cancer"],
    "종양":         ["tumor", "cancer", "neoplasm"],
    "항암":         ["chemotherapy", "cancer treatment", "anticancer"],
    "수술":         ["surgery", "operation"],
    "치료":         ["treatment", "therapy", "cure"],
    "심장":         ["heart", "cardiac", "cardiovascular"],
    "심박":         ["heart rate", "pulse", "cardiac rate"],
    "혈압":         ["blood pressure", "hypertension", "pressure"],
    "뇌":           ["brain", "cerebral", "neural"],
    "신경":         ["nerve", "neural", "neurological"],
    "뇌졸중":       ["stroke", "cerebral stroke", "brain attack"],
    "피부":         ["skin", "dermal", "cutaneous"],
    "피부과":       ["dermatology", "skin care", "skin clinic"],
    "알레르기":     ["allergy", "allergic", "allergen"],
    "모자":         ["hat", "cap", "headwear"],
    "헬멧":         ["helmet", "protective gear"],
    "조명":         ["lighting", "light", "illumination"],
    "전등":         ["lamp", "light", "bulb"],
    "빛":           ["light", "glow", "beam", "ray"],
    "약":           ["medicine", "drug", "medication"],
    "과학":         ["science", "scientific"],
    "연구":         ["research", "study"],
    "실험":         ["experiment", "test"],
    "우주":           ["space", "universe", "cosmos", "cosmic"],
    "코스모스":       ["cosmos", "space", "universe"],
    "보이저":         ["Voyager", "spacecraft", "space probe"],
    "보이저호":       ["Voyager", "Voyager spacecraft", "space probe"],
    "골든디스크":     ["golden record", "golden disk", "Voyager record"],
    "골든":           ["golden", "gold"],
    "탐사선":         ["space probe", "probe", "spacecraft", "explorer"],
    "탐사":           ["exploration", "probe", "expedition"],
    "우주선":         ["spacecraft", "spaceship", "rocket"],
    "위성":           ["satellite", "orbital"],
    "인공위성":       ["satellite", "artificial satellite"],
    "로켓":           ["rocket", "launch vehicle"],
    "환경":         ["environment", "environmental"],
    "기후":         ["climate"],
    "지진":           ["earthquake"],
    "홍수":         ["flood"],
    "미세먼지":     ["fine dust", "PM2.5", "particulate matter", "air pollution"],
    "대기":         ["air", "atmosphere", "atmospheric"],
    "오염":         ["pollution", "contamination", "pollutant"],
    "재활용":       ["recycling", "recycle", "sustainable"],
    "쓰레기":       ["waste", "garbage", "trash", "refuse"],
    "분리수거":     ["waste sorting", "recycling", "separate collection"],
    "폐기물":       ["waste", "garbage", "refuse"],
    "종교":         ["religion", "religious", "faith"],
    "불교":         ["Buddhism", "Buddhist"],
    "기독교":       ["Christianity", "Christian"],
    "이슬람":       ["Islam", "Muslim"],
    "신앙":         ["faith", "religion", "belief"],
    "비만":         ["obesity", "overweight", "obese"],
    "당뇨":         ["diabetes", "diabetic"],
    "고혈압":       ["hypertension", "high blood pressure"],
    # EN→KO 의료/환경/건강 역방향
    "health":       ["건강", "보건"],
    "healthy":      ["건강한", "건강"],
    "medical":      ["의료", "의학", "의학적"],
    "healthcare":   ["의료", "보건"],
    "disease":      ["질병", "병"],
    "vaccine":      ["백신", "예방접종"],
    "cancer":       ["암", "암질환"],
    "treatment":    ["치료", "치료법"],
    "surgery":      ["수술"],
    "pandemic":     ["팬데믹", "코로나"],
    "covid":        ["코로나", "코비드"],
    "coronavirus":  ["코로나", "코로나바이러스"],
    "environment":  ["환경", "자연환경"],
    "environmental": ["환경", "환경적"],
    "climate":      ["기후", "기후변화", "온난화"],
    "warming":      ["온난화", "기온상승", "지구온난화"],
    "temperature":  ["기온", "온도", "체온"],
    "pollution":    ["오염", "공해", "미세먼지"],
    "dust":         ["먼지", "미세먼지"],
    "air":          ["공기", "대기", "대기오염"],
    "recycling":    ["재활용", "분리수거"],
    "waste":        ["쓰레기", "폐기물", "낭비"],
    "sorting":      ["분류", "분리수거"],
    "religion":     ["종교", "신앙"],
    "religious":    ["종교적", "종교"],
    "buddhism":     ["불교", "불교적"],
    "buddhist":     ["불교", "불교인"],
    "christianity": ["기독교", "기독교적"],
    "christian":    ["기독교", "기독교인"],
    "faith":        ["신앙", "종교", "믿음"],
    "research":     ["연구", "조사"],
    "experiment":   ["실험", "연구"],
    "earthquake":   ["지진"],
    "flood":        ["홍수"],
    "obesity":      ["비만", "과체중"],
    "diabetes":     ["당뇨", "당뇨병"],
    "hypertension": ["고혈압", "혈압"],
    "overweight":   ["비만", "과체중"],
    # 정신건강/심리
    "우울증":       ["depression", "depressive", "mental health"],
    "우울":         ["depression", "depressed", "sadness"],
    "불안":         ["anxiety", "anxious", "worry"],
    "정신건강":     ["mental health", "psychology", "psychological"],
    "정신질환":     ["mental illness", "psychiatric disorder"],
    "심리":         ["psychology", "psychological", "mental"],
    "심리학":       ["psychology", "psychological"],
    "상담치료":     ["counseling", "therapy", "psychotherapy"],
    "스트레스":     ["stress", "pressure", "burnout"],
    "명상":         ["meditation", "mindfulness", "relaxation"],
    "자살":         ["suicide", "suicidal"],
    "치매":         ["dementia", "Alzheimer"],
    # EN→KO 정신건강 역방향
    "depression":   ["우울증", "우울"],
    "anxiety":      ["불안", "불안감"],
    "mental":       ["정신", "정신건강"],
    "psychology":   ["심리", "심리학"],
    "psychological": ["심리적", "심리"],
    "therapy":      ["치료", "상담"],
    "stress":       ["스트레스", "압박"],
    "meditation":   ["명상", "마음챙김"],
    "dementia":     ["치매", "알츠하이머"],

    # ── 사회 / 생활 ────────────────────────────────────────────────
    "사회":         ["society", "social"],
    "문화":         ["culture", "cultural"],
    "역사":           ["history", "historical"],
    "교육":           ["education", "educational"],
    "대학교":       ["university", "college", "higher education"],
    "입시":         ["entrance exam", "university admissions", "college entrance"],
    "수능":         ["CSAT", "university entrance exam", "college entrance exam"],
    "졸업":         ["graduation", "graduate", "commencement"],
    "학위":         ["degree", "diploma", "academic degree"],
    "석사":         ["master", "graduate degree", "postgraduate"],
    "박사":         ["PhD", "doctorate", "doctoral"],
    "건설":         ["construction", "building", "development"],
    "공사":         ["construction", "construction work", "building work"],
    "시공":         ["construction", "installation", "building"],
    "원전":         ["nuclear power plant", "nuclear reactor", "nuclear energy"],
    "방사능":       ["radiation", "radioactive", "nuclear radiation"],
    "취업":         ["employment", "employ", "job", "career"],
    "취준":           ["job seeking", "job hunting"],
    "이민":         ["immigration", "immigrant"],
    "저출생":       ["low birth rate", "declining birth rate"],
    "고령화":       ["aging society", "aging population"],
    "청년":         ["youth", "young people"],
    "노동":         ["labor", "work"],
    "임금":         ["wage", "salary"],
    "파업":         ["strike"],
    "범죄":         ["crime", "criminal"],
    "수사":         ["investigation", "criminal investigation", "probe"],
    "체포":         ["arrest", "detained", "apprehend"],
    "구속":         ["detention", "arrest", "custody"],
    "구금":         ["detention", "imprisonment"],
    "기소":         ["prosecution", "indictment", "charge"],
    "판결":         ["verdict", "ruling", "sentence"],
    "형사":         ["detective", "criminal", "investigator"],
    "사고":         ["accident", "incident"],
    "재난":         ["disaster", "calamity", "catastrophe"],
    "재해":         ["disaster", "calamity", "damage"],
    "피해":         ["damage", "harm", "victim"],
    "부상":         ["injury", "wound"],
    "화재":         ["fire", "blaze"],
    "폭발":         ["explosion", "blast"],
    "태풍":         ["typhoon", "hurricane", "tropical storm"],
    "교통":         ["traffic", "transportation"],
    "교통사고":     ["traffic accident", "car accident", "crash"],
    "부패":         ["corruption"],
    "인권":         ["human rights"],
    "직업":         ["job", "career", "profession", "occupation"],
    "구직":         ["job search", "job hunting", "employment"],
    "경력":         ["career", "work experience", "experience"],
    "이직":         ["job change", "career change", "transfer"],
    "계획":         ["plan", "planning", "scheme"],
    "계획서":       ["plan", "planning document", "blueprint"],
    "제안":         ["proposal", "suggestion", "propose"],
    "제안서":       ["proposal", "proposal document"],
    "명절":         ["holiday", "traditional holiday", "festival"],
    "추석":         ["Chuseok", "Korean Thanksgiving", "harvest festival"],
    "설날":         ["Seollal", "Lunar New Year", "Korean New Year"],
    "공휴일":       ["public holiday", "national holiday"],
    "휴일":         ["holiday", "day off"],
    "결혼":         ["marriage", "wedding", "matrimony"],
    "이혼":         ["divorce", "separation"],
    "가정":         ["family", "household", "home"],
    "육아":         ["parenting", "childcare", "child rearing"],
    "임신":         ["pregnancy", "pregnant"],
    "출산":         ["childbirth", "birth", "delivery"],
    # EN→KO 사회/가정 역방향
    "marriage":     ["결혼", "혼인"],
    "wedding":      ["결혼", "결혼식", "웨딩"],
    "divorce":      ["이혼", "별거"],
    "household":    ["가정", "가구"],
    "parenting":    ["육아", "자녀양육"],
    "pregnancy":    ["임신", "임신기"],
    "childbirth":   ["출산", "분만"],

    # ── 국제 / 외교 ────────────────────────────────────────────────
    "미국":         ["US", "USA", "United States", "America", "American"],
    "중국":         ["China", "Chinese"],
    "일본":         ["Japan", "Japanese"],
    "북한":         ["North Korea", "DPRK"],
    "러시아":       ["Russia", "Russian"],
    "유럽":         ["Europe", "European"],
    "외교":         ["diplomacy", "diplomatic"],
    "정상회담":     ["summit", "summit meeting"],
    "군사":         ["military", "armed forces"],
    "전쟁":         ["war", "warfare", "conflict"],
    "평화":         ["peace", "ceasefire"],
    "제재":         ["sanctions", "penalty"],
    "트럼프":       ["Trump"],
    "바이든":       ["Biden"],
    "미사일":       ["missile", "ballistic missile", "ICBM"],
    "핵":           ["nuclear", "atomic"],
    "핵무기":       ["nuclear weapon", "nuclear bomb", "nuclear"],
    "핵발전":       ["nuclear power", "nuclear energy"],
    "방위":         ["defense", "defence"],
    "안보":         ["security", "national security", "defense"],
    "국방":         ["national defense", "defense", "military"],
    "분쟁":         ["conflict", "dispute", "tension"],
    "협상":         ["negotiation", "talks", "dialogue"],
    "휴전":         ["ceasefire", "armistice", "truce"],
    "군대":         ["army", "troops", "military"],
    "병력":         ["troops", "military force"],
    "무기":         ["weapon", "arms", "weaponry"],
    "포격":         ["shelling", "bombardment", "attack"],
    "침공":         ["invasion", "attack", "aggression"],
    "동맹":         ["alliance", "ally", "coalition"],
    "한미":         ["Korea US", "South Korea United States"],
    # EN→KO 국제/외교 역방향
    "war":          ["전쟁", "분쟁"],
    "military":     ["군사", "군대"],
    "peace":        ["평화", "화해"],
    "diplomacy":    ["외교"],
    "diplomatic":   ["외교적", "외교"],
    "summit":       ["정상회담", "정상"],
    "sanctions":    ["제재", "경제제재"],
    "missile":      ["미사일", "탄도미사일"],
    "nuclear":      ['핵', '핵무기', '원자력', '원전'],
    "atomic":       ["원자", "핵"],
    "defense":      ["국방", "방위", "안보"],
    "defence":      ["국방", "방위", "안보"],
    "security":     ["안보", "보안", "안전"],
    "conflict":     ["분쟁", "갈등", "전쟁"],
    "negotiation":  ["협상", "협상안"],
    "negotiations": ["협상", "대화"],
    "troops":       ["군대", "병력"],
    "weapon":       ["무기", "병기"],
    "weapons":      ["무기", "군사"],
    "alliance":     ["동맹", "연합"],
    "invasion":     ["침공", "침략"],
    "ceasefire":    ["휴전", "정전"],
    # EN→KO 사회/문화 역방향
    "society":      ["사회"],
    "social":       ['사회', '사회적', '소셜', 'SNS'],
    "culture":      ["문화"],
    "cultural":     ["문화적", "문화"],
    "history":      ["역사"],
    "historical":   ["역사적", "역사"],
    "education":    ["교육"],
    "educational":  ["교육적", "교육"],
    "crime":        ["범죄", "범행"],
    "criminal":     ["범죄자", "범죄"],
    "investigation": ["수사", "조사"],
    "investigate":  ["수사", "조사"],
    "arrest":       ["체포", "구속"],
    "detained":     ["구금", "체포"],
    "detention":    ["구금", "구속"],
    "prosecution":  ["기소", "검찰"],
    "verdict":      ["판결", "선고"],
    "police":       ["경찰", "경찰청"],
    "detective":    ["형사", "탐정"],
    "disaster":     ["재난", "재해"],
    "calamity":     ["재난", "재해"],
    "catastrophe":  ["재해", "재난"],
    "typhoon":      ["태풍"],
    "hurricane":    ["태풍", "허리케인"],
    "explosion":    ["폭발"],
    "blaze":        ["화재"],
    "damage":       ["피해", "손해"],
    "injury":       ["부상", "부상자"],
    "accident":     ["사고", "교통사고"],
    "career":       ["직업", "경력", "취업"],
    "profession":   ["직업", "전문직"],
    "occupation":   ["직업", "직종"],
    "job":          ["직업", "일자리", "취업"],
    "hiring":       ["채용", "고용"],
    "employment":   ["취업", "고용"],
    "corruption":   ["부패", "비리"],
    "labor":        ["노동", "근로"],
    "youth":        ["청년", "젊은이"],
    "aging":        ["고령화", "노인"],
    "immigration":  ["이민", "이주"],

    # ── 여행 / 관광 / 축제 ────────────────────────────────────────
    "여행":         ["travel", "trip", "journey", "tour"],
    "관광":         ["tourism", "sightseeing", "travel"],
    "축제":         ["festival", "celebration", "event"],
    "투어":         ["tour", "travel"],
    "해외":         ["overseas", "abroad", "international"],
    "외국":         ["foreign", "overseas", "abroad"],
    "국내":         ["domestic", "local", "nationwide"],
    "해외여행":     ["overseas travel", "international travel", "abroad"],
    "관광지":       ["tourist attraction", "sightseeing spot", "landmark"],
    "호텔":         ["hotel", "accommodation"],
    "카페":         ["cafe", "coffee shop"],
    # 아웃도어/레저
    "등산":         ["hiking", "mountain climbing", "trekking"],
    "산행":         ["hiking", "mountain hike", "trekking"],
    "트레킹":       ["trekking", "hiking", "trail"],
    "캠핑":         ["camping", "camp", "outdoor"],
    "백패킹":       ["backpacking", "camping", "trekking"],
    "낚시":         ["fishing", "angling"],
    "서핑":         ["surfing", "surf"],
    "스노보드":     ["snowboarding", "snowboard"],
    "자전거":       ["bicycle", "cycling", "bike"],
    # EN→KO 아웃도어 역방향
    "hiking":       ["등산", "산행", "트레킹"],
    "trekking":     ["트레킹", "등산"],
    "camping":      ["캠핑", "야영"],
    "trek":         ["트레킹", "등산"],
    "climb":        ["등반", "등산"],
    "climbing":     ["등반", "등산", "클라이밍"],
    "fishing":      ["낚시"],
    "surfing":      ["서핑"],
    "skiing":       ["스키"],
    "cycling":      ["자전거", "사이클"],
    "bicycle":      ["자전거"],
    "backpacking":  ["백패킹", "배낭여행"],
    "다큐":         ["documentary", "documentary film"],  # 다큐멘터리 단축형
    "대상":           ["grand prize", "award", "winner", "top award", "main award"],
    "수상":           ["award", "prize", "win", "award winning", "winning award", "receiving award"],
    "시상":           ["award", "ceremony", "presentation", "awarding"],
    "예술":         ["art", "arts", "artistic"],
    "미술":         ["art", "painting", "fine art"],
    "전시":         ["exhibition", "exhibit", "display"],
    "공예":         ["craft", "craftsmanship"],
    "건축":         ["architecture", "building design"],

    # ── 업무 / 문서 ────────────────────────────────────────────────
    "회의":         ["meeting", "conference"],
    "발표":         ["presentation", "report", "announcement"],
    "강의":         ["lecture", "lesson"],
    "분석":         ["analysis", "analytical"],
    "운영":         ["operation"],
    "관리":         ["management", "manage"],
    "개발":         ["development", "develop"],
    "지원":         ["support"],
    "보고서":       ["report", "white paper"],
    "연간보고서":   ["annual report", "yearly report"],
    "실태조사":     ["industry survey", "survey report", "research report"],
    "통계":         ["statistics", "statistical"],
    "정책":         ["policy", "policies"],
    "산업":         ["industry", "industrial"],
    "기업":         ["company", "enterprise", "corporation"],
    "서비스":       ["service"],
    "이력서":       ["resume", "CV", "curriculum vitae"],
    "채용":         ["recruitment", "hiring", "job opening"],
    "계약":         ["contract", "agreement"],
    "합의":         ["agreement", "consensus"],
    "규정":         ["regulation", "rule"],
    "지침":         ["guideline", "directive"],
    "기준":         ["standard", "criteria"],
    "허가":         ["permit", "approval", "license"],
    "신고":         ["report", "declaration", "filing"],
    "감사":         ["audit", "inspection"],
    "주민등록증":   ["resident registration", "id card", "ID"],
    "운전면허증":   ["driver license", "driver's license"],
    "신분증":       ["id card", "ID", "identification"],
    "여권":         ["passport"],
    # EN→KO 업무/문서 역방향 (doc 도메인 쿼리 커버리지)
    "report":       ["보고서", "보도"],
    "document":     ["문서", "서류"],
    "documents":    ["문서", "서류"],
    "industry":     ["산업", "산업분야"],
    "industrial":   ["산업", "산업적"],
    "company":      ["기업", "회사"],
    "enterprise":   ["기업", "회사"],
    "corporation":  ["기업", "법인"],
    "annual":       ["연간", "연례"],
    "yearly":       ["연간", "연례"],
    "survey":       ["실태조사", "조사"],
    "statistics":   ["통계", "통계청"],
    "statistical":  ["통계적", "통계"],
    "analysis":     ["분석"],
    "analytical":   ["분석적", "분석"],
    "management":   ["관리", "경영"],
    "development":  ["개발", "발전"],
    "service":      ["서비스"],
    "recruitment":  ["채용", "모집"],
    "regulation":   ["규정", "규제"],
    "guideline":    ["지침", "가이드라인"],
    "standard":     ["기준", "표준"],
    "audit":        ["감사", "검사"],
    "contract":     ["계약", "협약"],
    "agreement":    ["합의", "협약"],
    "sustainability": ["지속가능성", "지속가능"],
    "sustainable":  ["지속가능한", "지속가능"],
    "지속가능성":   ["sustainability", "sustainable development"],
    "지속가능":     ["sustainable", "sustainability"],
    "삼성":         ["Samsung", "Samsung Electronics"],
    "삼성전자":     ["Samsung Electronics", "Samsung"],
    "Samsung":      ["삼성", "삼성전자"],
    "Electronics":  ["전자", "전자제품"],
    "전자제품":     ["electronics", "electronic products"],
    "index":        ["지수", "인덱스"],
    "agriculture":  ["농업", "농업분야"],
    "agricultural": ["농업", "농산"],
    "FAO":          ["FAO", "식량농업기구"],
    "식량":         ["food", "food supply", "grain", "staple"],
    "가격":         ["price", "cost", "value"],
    "지수":         ["index", "indicator", "score"],
    "농업":         ["agriculture", "agricultural", "farming"],
    "농산물":       ["agricultural product", "farm produce"],
    "수확":         ["harvest", "crop"],
    "semiconductor": ["반도체"],
    "software":     ["소프트웨어"],
    "hardware":     ["하드웨어"],
    "platform":     ['플랫폼', '서비스'],

    # ── 장소/지역 보조 ─────────────────────────────────────────────
    "지하":         ["basement", "underground", "subway"],
    "텍스트":       ["text"],
    "캡션":         ["caption"],
    # 국가/지역 고유명사
    "한국":         ["Korea", "Korean", "South Korea"],
    "서울":         ["Seoul"],
    "부산":         ["Busan"],
    "대한민국":     ["Korea", "Republic of Korea", "South Korea"],
    "코리아":       ["Korea", "Korean"],
    # EN→KO 지역 역방향
    "korea":        ["한국", "대한민국"],
    "korean":       ["한국", "한국어", "한국인"],
    "seoul":        ["서울"],

    # ── 색상 ──────────────────────────────────────────────────────
    "빨간":         ["red"],
    "빨간색":       ["red", "scarlet", "crimson"],
    "붉은":         ["red", "crimson", "scarlet"],
    "파란":         ["blue"],
    "파란색":       ["blue", "azure"],
    "노란":         ["yellow"],
    "노란색":       ["yellow", "golden"],
    "초록":         ["green"],
    "초록색":       ["green", "emerald"],
    "흰":           ["white"],
    "흰색":         ["white", "bright", "pale"],
    "검은":         ["black"],
    "검은색":       ["black", "dark"],
    "색깔":         ["color", "colored", "colorful"],
    "색상":         ["color", "colours", "tone"],
    "색":           ["color", "hue", "shade"],
    "시계":         ["watch", "clock", "timepiece"],
    "손목":         ["wrist", "wristwatch"],
    "손목시계":     ["wristwatch", "watch", "timepiece"],

    # ── 음악 / BGM ────────────────────────────────────────────────
    "음악":         ["music", "musical"],
    "노래":         ["song", "songs", "vocal"],
    "피아노":       ["piano", "piano music"],
    "기타":         ["guitar", "guitar music"],
    "드럼":         ["drum", "drums", "percussion"],
    "오케스트라":   ["orchestra", "orchestral", "symphonic"],
    "발라드":       ["ballad", "ballads"],
    "댄스":         ["dance", "dancing"],
    "록":           ["rock", "rock music", "rock band"],
    "재즈":         ["jazz", "jazz music"],
    "클래식":       ["classical", "classical music"],
    "전자":         ["electronic", "electronic music", "EDM"],
    "팝":            ["pop", "pop music"],
    "팝송":         ["pop song", "pop music", "pop"],
    "가요":         ["Korean song", "K-pop", "Korean music", "Korean pop"],
    "힙합":           ["hip hop", "rap", "hip-hop"],
    "인디":         ["indie", "indie music"],
    "소울":         ["soul", "soul music", "R&B"],
    "포크":         ["folk", "folk music"],
    "컨트리":       ["country", "country music"],
    # EN→KO 음악 장르 역방향 명시 (auto-gen 보완)
    "rock":         ["록", "록음악", "락"],
    "jazz":         ["재즈", "재즈음악"],
    "classical":    ["클래식", "클래식음악", "고전음악"],
    "ballad":       ["발라드", "발라드곡"],
    "electronic":   ["전자", "전자음악", "일렉트로닉"],
    "acoustic":     ["어쿠스틱", "통기타"],
    "instrumental": ["악기", "연주곡", "연주"],
    "melody":       ["멜로디", "선율"],
    "rhythm":       ["리듬", "박자"],
    # "hip hop"은 2-word → 토크나이저가 ["hip","hop"]으로 분리 → 각 토큰에 역방향 등록
    "hip":          ["힙합", "힙합음악"],
    "hop":          ["힙합"],
    "rap":          ["랩", "힙합", "랩음악"],
    "rapper":       ["랩퍼", "힙합"],
    "hiphop":       ["힙합"],
    "pop":          ["팝", "팝음악"],
    "folk":         ["포크", "포크음악"],
    "country":      ["컨트리", "컨트리음악"],
    "soul":         ["소울", "소울음악"],
    "indie":        ["인디", "인디음악"],
    "ambient":      ["앰비언트", "배경음악"],
    "lofi":         ["로파이", "lo-fi", "배경음악"],
    "beat":         ["비트", "리듬"],
    "악기":         ["instrument", "instrumental"],
    "보컬":         ["vocal", "vocals"],
    "분위기":       ["mood", "vibe", "atmosphere"],
    "잔잔한":       ["calm", "peaceful", "soothing", "mellow"],
    "신나는":       ["upbeat", "energetic", "lively", "exciting"],
    "조용한":       ["quiet", "silent", "soft", "gentle"],
    "밝은":         ["bright", "cheerful", "happy", "positive"],
    "어두운":       ["dark", "gloomy", "somber", "dim"],
    "빠른":         ["fast", "upbeat", "energetic", "driving"],
    "느린":         ["slow", "calm", "relaxed", "laid-back"],
    "감성":         ["emotional", "sentimental", "atmospheric"],
    # BGM mood & tension terms
    "긴장":         ["tense", "tension", "suspenseful", "dramatic"],
    "긴장감":       ["tension", "tense", "suspense", "dramatic intensity"],
    "드라마틱":     ["dramatic", "cinematic", "epic"],
    "웅장한":       ["epic", "grand", "majestic", "orchestral"],
    "슬픈":         ["sad", "melancholic", "sorrowful", "melancholy"],
    "우울한":       ["sad", "melancholic", "depressing", "gloomy"],
    "활기찬":       ["lively", "vibrant", "energetic", "vivid"],
    "경쾌한":       ["cheerful", "light", "bouncy", "lively"],
    "로맨틱":       ["romantic", "love", "tender", "intimate"],
    "신비로운":     ["mysterious", "mystical", "ethereal", "ambient"],
    "편안한":       ["relaxing", "comfortable", "cozy", "soothing"],
    "몽환적":       ["dreamy", "ethereal", "hazy", "ambient"],
    "강렬한":       ["intense", "powerful", "strong", "forceful"],
    "부드러운":     ["smooth", "soft", "gentle", "mellow"],
    "따뜻한":       ["warm", "cozy", "heartwarming", "gentle"],
    "차가운":       ["cold", "cool", "icy", "stark"],
    "R&B":          ["R&B", "rhythm and blues"],
    "트로트":       ["trot", "Korean trot"],
    "한류":         ["Korean wave", "hallyu", "K-pop", "K-culture"],
    "케이팝":       ["K-pop", "kpop", "Korean pop", "Korean idol"],
    # EN→KO K-pop/hallyu 역방향
    "kpop":         ["케이팝", "가요", "아이돌"],
    "hallyu":       ["한류", "케이팝"],
    "trot":         ["트로트", "한국 트로트"],
    "idol":         ["아이돌", "케이팝"],
    "국악":         ["Korean traditional music", "gugak"],
    "OST":          ["OST", "soundtrack", "original soundtrack"],
    "영화음악":     ["film score", "soundtrack", "cinematic", "movie music", "film music", "OST"],
    "사운드트랙":   ["soundtrack", "OST", "film score"],
    "영화음악가":   ["film composer", "composer", "film score"],
    "배경음악":     ["background music", "BGM"],
    "반주":         ["accompaniment", "background music"],
    # BGM mood / genre (추가 — query_expand 4차)
    "힐링":         ["healing", "relaxing", "soothing", "calming", "therapeutic"],
    "치유":         ["healing", "therapeutic", "soothing", "restorative"],
    "레트로":       ["retro", "vintage", "nostalgic", "oldschool", "classic"],
    "복고":         ["retro", "vintage", "nostalgic", "old-fashioned"],
    "빈티지":       ["vintage", "retro", "nostalgic", "classic", "oldschool"],
    "자연소리":     ["nature sounds", "natural sounds", "ambient nature", "birds", "rain sounds"],
    "자연 소리":    ["nature sounds", "natural sounds", "ambient nature"],
    "새소리":       ["bird sounds", "birds chirping", "birdsong", "nature"],
    "빗소리":       ["rain sounds", "rainfall", "rain ambience", "nature"],
    "파도소리":     ["ocean waves", "wave sounds", "sea sounds", "nature"],
    "카페음악":     ["cafe music", "coffee shop music", "lofi", "chill", "background music"],
    "카페 음악":    ["cafe music", "coffee shop music", "lofi", "chill"],
    "공부":         ["study", "studying", "learning", "focus"],
    "공부음악":     ["study music", "focus music", "concentration music", "lofi", "ambient"],
    "공부 음악":    ["study music", "focus music", "concentration music", "lofi"],
    "집중":         ["focus", "concentration", "study", "productivity"],
    "집중음악":     ["focus music", "concentration music", "study music", "lofi"],
    # EN→KO BGM mood / genre 역방향
    "healing":      ["힐링", "치유", "잔잔한", "편안한"],
    "retro":        ["레트로", "복고", "빈티지", "향수"],
    "vintage":      ["빈티지", "레트로", "복고"],
    "nostalgic":    ["향수", "레트로", "그리운"],
    "oldschool":    ["레트로", "복고", "클래식"],
    "nature sounds": ["자연소리", "자연"],
    "cafe music":   ["카페음악", "카페 음악", "로파이"],
    "coffee shop":  ["카페", "카페음악", "로파이"],
    "study music":  ["공부음악", "집중음악", "로파이", "집중"],
    "focus music":  ["집중음악", "공부음악", "로파이"],
    "bird sounds":  ["새소리", "자연소리"],
    "rain sounds":  ["빗소리", "자연소리"],
    "ocean waves":  ["파도소리", "파도", "자연소리"],
    "일자리":       ["job", "work", "position", "employment", "post"],
    "고용":         ["employment", "hiring", "job", "hire"],
    "구인":         ["job opening", "recruitment", "hiring"],
    "실업":         ["unemployment", "jobless"],
    "실직":         ["job loss", "unemployment", "layoff"],

    # ── 악기 / 음악 상세 ──────────────────────────────────────────────
    "첼로":         ["cello"],
    "바이올린":     ["violin"],
    "플루트":       ["flute"],
    "색소폰":       ["saxophone", "sax"],
    "트럼펫":       ["trumpet"],
    "베이스기타":   ["bass guitar", "bass"],
    "신디사이저":   ["synthesizer", "synth"],
    "전자기타":     ["electric guitar"],
    "어쿠스틱":     ["acoustic"],
    "현악기":       ["strings", "string instrument"],
    "관악기":       ["wind instrument", "brass", "woodwind"],
    "타악기":       ["percussion", "drums"],
    "앙상블":       ["ensemble"],
    "협주곡":       ["concerto"],
    "교향곡":       ["symphony"],
    "멜로디":       ["melody"],
    "화음":         ["harmony", "chord"],
    "박자":         ["rhythm", "tempo", "beat"],
    "비트":         ["beat", "rhythm", "groove"],
    "전주":         ["intro", "introduction", "prelude"],
    "후렴":         ["chorus", "refrain"],
    "간주":         ["interlude", "bridge"],

    # ── 영화 / 드라마 상세 ────────────────────────────────────────────
    "출연":         ["starring", "appearance", "cast", "featured"],
    "주연":         ["lead actor", "starring", "leading role"],
    "조연":         ["supporting actor", "co-star"],
    "주인공":       ["protagonist", "lead", "main character", "hero"],
    "제목":         ["title"],
    "개봉":         ["release", "premiere", "opening"],
    "상영":         ["screening", "showing"],
    "예고편":       ["trailer", "preview"],
    "결말":         ["ending", "finale", "conclusion"],
    "줄거리":       ["plot", "synopsis", "storyline", "story"],
    "한줄평":       ["tagline", "one-liner", "review", "short review"],
    "평점":         ["rating", "score", "evaluation"],
    "리뷰":         ["review", "critique", "criticism"],
    "관람":         ["watching", "viewing", "attendance"],
    "속편":         ["sequel", "follow-up"],
    "프리퀄":       ["prequel"],
    "원작":         ["original", "source material", "based on"],
    "영화제":       ["film festival", "festival"],
    "장르":         ["genre"],
    "감동":         ["touching", "moving", "emotional", "heartwarming"],
    "명장면":       ["best scene", "iconic scene", "highlight scene"],
    # EN → KO 영화 도메인 역방향 (auto-generated 로 커버 안 되는 단어 추가)
    "plot":         ["줄거리"],
    "synopsis":     ["줄거리", "내용"],
    "tagline":      ["한줄평"],
    "rating":       ["평점", "점수"],
    "review":       ["리뷰", "평점", "한줄평"],
    "sequel":       ["속편"],
    "prequel":      ["프리퀄"],
    "protagonist":  ["주인공"],
    "starring":     ["주연", "출연"],
    "genre":        ["장르"],
    "trailer":      ["예고편"],
    "festival":     ["영화제", "축제"],
    "travel":       ["여행", "관광"],
    "trip":         ["여행"],
    "tourism":      ["관광", "여행"],
    "tour":         ["투어", "여행", "관광"],
    "overseas":     ["해외", "국제"],
    "abroad":       ["해외", "외국"],
    "foreign":      ["외국", "해외"],
    "documentary":  ["다큐멘터리", "다큐"],
    "concert":      ["공연", "콘서트"],
    "performance":  ["공연", "공연자"],
    "exhibition":   ["전시", "전시회"],
    "ceremony":     ["시상식", "행사"],
    "award":        ["수상", "시상식", "대상"],
    "artwork":      ["미술", "예술작품"],

    # ── 스포츠 상세 ───────────────────────────────────────────────────
    "스타":         ["star", "celebrity"],
    "팀":           ["team", "squad"],
    "심판":         ["referee", "judge", "umpire"],
    "코치":         ["coach", "trainer"],
    "공격":         ["attack", "offense", "offensive"],
    "수비":         ["defense", "defensive"],
    "골":           ["goal"],
    "점수":         ["score", "point", "points"],
    "우승":         ["championship", "win", "victory", "title"],
    "준우승":       ["runner-up", "second place"],
    "기록":         ["record"],

    # ── 영상 / 방송 고유명사 ─────────────────────────────────────
    "유퀴즈":       ["You Quiz", "variety show"],
    "뉴스하이킥":   ["News High Kick", "news show"],
    "오뚝이":       ["comeback", "resilience"],
    "MBC":          ["MBC", "Munhwa Broadcasting"],
    "KBS":          ["KBS", "Korea Broadcasting"],
    "SBS":          ["SBS"],
    "JTBC":         ["JTBC"],
    "MBN":          ["MBN"],

    # ── 과학 / 학문 ─────────────────────────────────────────────────
    "물리":         ["physics", "physical"],
    "물리학":       ["physics", "physics science"],
    "양자":         ["quantum"],
    "양자역학":     ["quantum mechanics", "quantum physics"],
    "화학":         ["chemistry", "chemical"],
    "생물":         ["biology", "biological"],
    "천문":         ["astronomy", "astronomical"],
    "수학":         ["mathematics", "math"],
    "진화":         ["evolution", "evolutionary"],
    "상대성이론":   ["relativity", "theory of relativity"],
    "중력":         ["gravity", "gravitation"],
    "의학":         ["medicine", "medical"],
    # EN→KO 과학 역방향
    "science":      ["과학", "과학기술"],
    "scientific":   ["과학적", "과학"],
    "physics":      ["물리", "물리학"],
    "quantum":      ["양자", "양자역학"],
    "chemistry":    ["화학"],
    "biology":      ["생물", "생물학"],
    "astronomy":    ["천문", "천문학"],
    "mathematics":  ["수학"],
    "math":         ["수학", "수학적"],
    "evolution":    ["진화", "진화론"],
    "gravity":      ["중력", "인력"],
    "relativity":   ["상대성이론", "상대성"],
    "medicine":     ["의학", "의료"],
    "space":        ["우주", "공간"],
    "universe":     ["우주", "우주론"],
    "cosmos":       ["우주", "코스모스"],
    "voyager":      ["보이저", "보이저호"],
    "golden":       ["골든", "황금"],
    "probe":        ["탐사선", "탐사"],
    "spacecraft":   ["우주선", "탐사선"],
    "satellite":    ["인공위성", "위성"],
    "rocket":       ["로켓", "우주선"],
    "exploration":  ["탐사", "탐험"],
    "nasa":         ["나사", "미항공우주국"],
    # 천문학자 / 과학자 고유명사
    "sagan":        ["세이건", "칼세이건"],
    "carl":         ["칼", "칼 세이건"],
    "hawking":      ["호킹", "스티븐호킹"],
    "einstein":     ["아인슈타인"],
    "newton":       ["뉴턴"],
    # 외계 생명체
    "alien":        ["외계인", "외계생명체", "외계"],
    "aliens":       ["외계인", "외계생명체"],
    "extraterrestrial": ["외계인", "외계생명체", "외계"],
    "ufo":          ["UFO", "비행물체", "외계"],

    # ── 역사 / 탐험 / 다큐멘터리 도메인 ─────────────────────────────────
    # 실크로드
    "실크로드":     ["silk road", "silkroad", "Silk Road"],
    "silk":         ["실크로드", "비단길"],
    "road":         ["실크로드", "비단길", "길"],
    "비단길":       ["silk road", "Silk Road"],
    # 고선지 / 실크로드 인물
    "고선지":       ["Gao Xianzhi", "Tang dynasty general", "silk road general"],
    "당나라":       ["Tang dynasty", "Tang", "Chinese dynasty", "Chinese empire"],
    # 인류 다큐 시리즈
    "흑사병":       ["Black Death", "plague", "pandemic"],
    "산업혁명":     ["Industrial Revolution", "industrialization"],
    "철기시대":     ["Iron Age"],
    "신대륙":       ["New World", "Americas", "Columbus"],
    "대항해":       ["Age of Exploration", "Age of Discovery", "great voyage"],
    "문명사":       ["history of civilization", "civilizational history"],
    # EN→KO 역방향
    "plague":       ["흑사병", "전염병", "역병"],
    "dynasty":      ["왕조", "당나라", "제국"],
    "medieval":     ["중세", "중세시대"],
    "ancient":      ["고대", "고대문명"],
    "empire":       ["제국", "당나라"],
    "conquest":     ["정복", "점령"],
    "expedition":   ["탐험", "원정", "탐사"],
    "revolution":   ["혁명", "산업혁명"],

    # ── AI / 개발 도구 고유명사 ───────────────────────────────────────
    "claude":       ["클로드", "Claude AI", "Anthropic"],
    "클로드":       ["Claude", "Claude AI", "Anthropic"],
    "chatgpt":      ["ChatGPT", "GPT", "OpenAI"],
    "gpt":          ["GPT", "ChatGPT", "언어모델"],
    "openai":       ["OpenAI", "GPT", "ChatGPT"],
    "anthropic":    ["Anthropic", "클로드"],
    "앤트로픽":     ["Anthropic", "Claude", "클로드"],
    "gemini":       ["Gemini", "Google AI"],
    "박태웅":       ["Park Taewung", "Park Tae-woong", "AI expert"],
    "taewung":      ["박태웅", "Park Tae-woong"],
    "샘":           ["Sam", "Sam Altman", "Samuel"],
    "알트먼":       ["Altman", "Sam Altman", "OpenAI CEO"],
    "altman":       ["알트먼", "샘 알트먼", "Sam Altman", "OpenAI"],
    "미토스":       ["Mythos", "AI model", "Anthropic"],
    "mythos":       ["미토스", "AI model"],
    "세이건":       ["Sagan", "Carl Sagan", "칼 세이건"],
    "외계인":       ["alien", "aliens", "extraterrestrial", "UFO"],
    "외계생명체":   ["extraterrestrial life", "alien life", "ET"],
    # ── 미디어 / 팟캐스트 ────────────────────────────────────────────
    "김어준":       ["Kim Eojun", "Das Beoida", "podcast", "시사"],
    "다스뵈이다":   ["Das Beoida", "김어준", "podcast", "시사"],
    # ── 개발 방법론 ──────────────────────────────────────────────────
    "바이브":       ["vibe", "vibe coding", "AI coding"],
    "바이브코딩":   ["vibe coding", "AI coding", "no-code", "바이브 코딩"],
    "바이브 코딩":  ["vibe coding", "AI coding", "no-code"],
    "vibe":         ["바이브", "바이브 코딩", "vibe coding"],
    "퀀트":         ["quant", "quantitative", "quantitative investing", "알고리즘 투자"],
    "quant":        ["퀀트", "quantitative", "알고리즘 투자"],

    # ── 교육 / 상담 ──────────────────────────────────────────────────
    "상담":         ["counseling", "consultation", "counselling"],
    "면담":         ["interview", "consultation meeting", "counseling session"],
    "선생님":       ["teacher", "instructor"],
    "수업":         ["class", "lesson", "lecture"],

    # ── 창업 / 사업 ──────────────────────────────────────────────────
    "창업":         ["startup", "entrepreneurship", "founding", "start-up"],
    "사업":         ["business", "enterprise"],
    "투자자":       ["investor"],
    "벤처":         ["venture", "startup"],
    "실리콘밸리":   ["Silicon Valley"],

    # ── 시상 / 행사 ──────────────────────────────────────────────────
    "연예":         ["entertainment", "celebrity"],

    # ── 분위기 / 형용사 ────────────────────────────────────────────
    "최신":         ["latest", "recent", "new"],
    "최고":         ["best", "top", "greatest"],
    "인기":         ["popular", "trending"],
    "화제":         ["trending", "hot topic", "buzz"],
    "논란":         ["controversy", "controversy", "issue"],
    "충격":         ["shock", "shocking"],
    "긴급":         ["urgent", "emergency", "breaking"],

    # ── 인류 / 역사 / 생명 ───────────────────────────────────────────
    "인류":         ["humanity", "human race", "mankind", "humankind"],
    "인간":         ["human", "human being", "people"],
    "문명":         ["civilization", "civilisation"],
    "생명":         ["life", "living", "organism", "biology"],
    "생존":         ["survival", "survivor", "survive"],
    "개척자":       ["pioneer", "pioneers", "explorer"],
    "전사":         ["warrior", "warriors", "soldier"],
    "생존자":       ["survivor", "survivors"],
    "발명":         ["invention", "inventor", "innovate"],
    "발명가":       ["inventor", "inventors", "innovator"],
    "속도":         ["speed", "velocity", "fast"],
    "철":           ["iron", "steel", "metal"],
    "행성":         ["planet", "planetary", "celestial body"],
    "태양":         ["sun", "solar", "sunshine"],
    "지구":         ["earth", "planet earth", "global", "world"],
    "별":           ["star", "stars", "stellar"],
    "은하":         ["galaxy", "galactic", "milky way"],
    "기원":         ["origin", "origins", "beginning"],
    "도시풍경":     ["cityscape", "urban landscape", "skyline"],

    # ── EN→KO 도시/야경/자연 역방향 ────────────────────────────────
    "skyline":      ["야경", "도시풍경", "스카이라인"],
    "cityscape":    ["도시풍경", "야경"],
    "nightscape":   ["야경", "야간"],
    "citylight":    ["야경", "도시"],
    "rooftop":      ["옥상", "루프탑"],

    # ── EN→KO 역방향 (인류/자연/역사) ────────────────────────────────
    "humanity":     ["인류", "인간"],
    "mankind":      ["인류", "인간"],
    "humankind":    ["인류", "인간"],
    "civilization": ["문명", "문화"],
    "survival":     ["생존", "생존자"],
    "survivor":     ["생존자", "생존"],
    "pioneer":      ["개척자", "탐험가"],
    "pioneers":     ["개척자들", "개척자"],
    "warrior":      ["전사", "군인"],
    "warriors":     ["전사들", "전사"],
    "invention":    ["발명", "발명품"],
    "inventor":     ["발명가", "발명자"],
    "planet":       ["행성", "지구"],
    "solar":        ["태양", "태양광"],
    "earth":        ["지구", "땅"],
    "galaxy":       ["은하", "은하계"],
    "origin":       ["기원", "출발"],
    "wildlife":     ["야생동물", "자연"],
    "tree":         ["나무", "숲"],

    # ── EN→KO 신체/의료 역방향 ───────────────────────────────────────
    "heart":        ["심장", "하트"],
    "cardiac":      ["심장", "심박"],
    "cardiovascular": ["심혈관", "심장"],
    "blood":        ["혈액", "피", "혈"],
    "pressure":     ["압력", "혈압"],
    "brain":        ["뇌", "두뇌"],
    "nerve":        ["신경", "신경계"],
    "stroke":       ["뇌졸중", "뇌경색"],
    "tumor":        ["종양", "암"],
    "chemotherapy": ["항암", "화학치료"],
    "skin":         ["피부", "살"],
    "allergy":      ["알레르기", "알러지"],
    "allergic":     ["알레르기", "과민반응"],
    "dermatology":  ["피부과", "피부학"],

    # ── EN→KO 의류/사물 역방향 ───────────────────────────────────────
    "hat":          ["모자", "캡"],
    "helmet":       ["헬멧", "모자"],
    "headwear":     ["모자", "헬멧"],
    "lamp":         ["전등", "조명"],
    "illumination": ["조명", "빛"],
    "lighting":     ["조명", "빛"],

    # ── EN→KO 미디어/소셜 역방향 ──────────────────────────────────────
    "instagram":    ["인스타그램", "SNS"],
    "twitter":      ["트위터", "SNS"],
    "tweet":        ["트윗", "트위터"],
    "blog":         ["블로그", "포스팅"],
    "post":         ["포스팅", "게시물"],
    "content":      ["콘텐츠", "내용"],
    "creator":      ["크리에이터", "유튜버", "창작자"],
    "streaming":    ["스트리밍", "스트림"],
    "netflix":      ["넷플릭스", "스트리밍"],

    # ── EN→KO 음식/음료 역방향 ────────────────────────────────────────
    "meal":         ["식사", "음식"],
    "recipe":       ["레시피", "요리법"],
    "chicken":      ["치킨", "닭고기"],
    "meat":         ["고기", "육류"],
    "beer":         ["맥주", "음주"],
    "wine":         ["와인", "술"],
    "alcohol":      ["술", "알코올", "음주"],
    "drink":        ["음료", "마시다", "술"],
    "sleep":        ["수면", "잠", "수면"],
    "insomnia":     ["불면증", "수면장애"],
    "rest":         ["휴식", "수면", "쉬다"],

    # ── EN→KO 교육 역방향 ─────────────────────────────────────────────
    "university":   ["대학교", "대학", "대학원"],
    "college":      ["대학교", "대학"],
    "graduation":   ["졸업", "졸업식"],
    "degree":       ["학위", "학력"],
    "master":       ["석사", "마스터"],
    "doctoral":     ["박사", "박사과정"],
    "exam":         ["시험", "입시", "수능"],
    "admissions":   ["입시", "입학"],

    # ── EN→KO 건설/에너지 역방향 ─────────────────────────────────────
    "construction": ["건설", "공사", "건축"],
    "building":     ["건물", "건설", "빌딩"],
    "site":         ["현장", "부지"],
    "radiation":    ["방사능", "방사선"],
    "radioactive":  ["방사능", "방사성"],

    # ── EN→KO 색상 역방향 ────────────────────────────────────────────
    "red":          ["빨간색", "빨간", "붉은"],
    "blue":         ["파란색", "파란", "파랑"],
    "yellow":       ["노란색", "노란", "노랑"],
    "green":        ["초록색", "초록", "녹색"],
    "white":        ["흰색", "흰", "하얀"],
    "black":        ["검은색", "검은", "검정"],
    "color":        ["색깔", "색상", "색"],
    "colorful":     ["알록달록", "컬러풀", "색깔"],
    "bright":       ["밝은", "환한", "빛나는"],
    "dark":         ["어두운", "암흑", "검은"],

    # ── EN→KO 시계/시간 역방향 ───────────────────────────────────────
    "clock":        ["시계", "벽시계", "시각"],
    "timepiece":    ["시계", "손목시계"],
    "wristwatch":   ["손목시계", "시계"],

    # ── EN→KO 계획/제안 역방향 ───────────────────────────────────────
    "plan":         ["계획", "계획서", "플랜"],
    "planning":     ["계획", "기획"],
    "proposal":     ["제안", "제안서", "프로포절"],
    "blueprint":    ["청사진", "계획서"],
    "project":      ["프로젝트", "사업"],

    # ── EN→KO 명절/휴일 역방향 ───────────────────────────────────────
    "holiday":      ["명절", "휴일", "공휴일"],
    "chuseok":      ["추석", "한가위"],
    "seollal":      ["설날", "설"],
    "lunar":        ["음력", "설날"],
    "thanksgiving": ["추수감사절", "추석"],
}

# 영 → 한 역방향 lookup (자동 생성)
_EN_KO: dict[str, list[str]] = {}
for _ko, _ens in _KO_EN.items():
    for _en in _ens:
        _EN_KO.setdefault(_en.lower(), []).append(_ko)


from functools import lru_cache


# 한국어 조사/어미 제거 (사전 매칭 전 전처리) — 길이순 내림차순 필수
_KO_PARTICLES = [
    "에서의", "으로서", "이라는", "이라고", "이지만", "이라도",
    "에서", "에게", "으로", "이라", "이나", "이고", "이면",
    "의", "을", "를", "이", "가", "은", "는", "로", "와", "과",
    "도", "만", "에", "서", "라", "나", "야",
]

def _strip_ko_particle(token: str) -> str:
    """한국어 토큰 끝의 조사를 제거하여 어근 반환."""
    for p in _KO_PARTICLES:
        if token.endswith(p) and len(token) > len(p) + 1:
            return token[: -len(p)]
    return token


@lru_cache(maxsize=4096)
def expand_bilingual(query: str, max_extra: int = 10) -> str:
    """쿼리를 한↔영 양방향 사전으로 확장.

    예:
      '어린이' → '어린이 children kids child'
      'cat' → 'cat 고양이'
      '취업 통계' → '취업 통계 employment statistics employ statistical'
      '산 풍경' (사전 미등록) → '산 풍경 mountain' (산만 매핑)
      '농구 하이라이트' → '농구 하이라이트 basketball highlight highlights'
      'economy news' → 'economy news 경제 뉴스 financial broadcast'

    Args:
      query: 원본 쿼리
      max_extra: 추가할 토큰 최대 수 (너무 많으면 sparse 노이즈)
                 default 10 (이전 8에서 증가 — 어휘 확장으로 커버리지 향상)
    """
    if not query or not query.strip():
        return query

    # 토큰 추출 — 한글/영문/숫자/대소문자 조합
    tokens = re.findall(r"[가-힣]+|[A-Za-z][A-Za-z0-9&/]*|[0-9]+", query)
    if not tokens:
        return query

    extras: list[str] = []
    seen: set[str] = {t.lower() for t in tokens}

    # 토큰별 최대 추가 수 제한 (per-token cap) — 단일 토큰이 max_extra 를 독점하지 않도록
    per_token_cap = max(2, max_extra // max(len(tokens), 1))

    for t in tokens:
        added_this_token = 0
        # 한 → 영: 직접 매칭 우선, 없으면 소문자 재시도, 없으면 조사 제거 후 재시도
        # (소문자 재시도: "Taewung"→"taewung", "Claude"→"claude" 등 대문자 입력 대응)
        t_lc = t.lower()
        t_root = t if t in _KO_EN else (t_lc if t_lc in _KO_EN else _strip_ko_particle(t))
        for en in _KO_EN.get(t_root, []):
            el = en.lower()
            if el not in seen:
                extras.append(en)
                seen.add(el)
                added_this_token += 1
                if added_this_token >= per_token_cap:
                    break
        # 영 → 한
        for ko in _EN_KO.get(t.lower(), []):
            if ko not in seen:
                extras.append(ko)
                seen.add(ko)
                added_this_token += 1
                if added_this_token >= per_token_cap:
                    break

    # 전체 상한 준수
    extras = extras[:max_extra]

    if not extras:
        return query
    return f"{query} {' '.join(extras)}"
